// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Course struct {
	ID          uuid.UUID      `json:"id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	OrgID       uuid.UUID      `json:"org_id"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Description string         `json:"description"`
	CoverImage  sql.NullString `json:"cover_image"`
	Status      string         `json:"status"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type CourseItem struct {
	ID        uuid.UUID     `json:"id"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	CourseID  uuid.UUID     `json:"course_id"`
	ContentID uuid.NullUUID `json:"content_id"`
	SortOrder int32         `json:"sort_order"`
	Title     string        `json:"title"`
	ItemType  string        `json:"item_type"`
}

type Enrolment struct {
	ID          uuid.UUID    `json:"id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	OrgID       uuid.UUID    `json:"org_id"`
	CourseID    uuid.UUID    `json:"course_id"`
	UserID      uuid.UUID    `json:"user_id"`
	Status      string       `json:"status"`
	EnrolledAt  time.Time    `json:"enrolled_at"`
	CompletedAt sql.NullTime `json:"completed_at"`
}

type H5pContent struct {
	ID          uuid.UUID       `json:"id"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	OrgID       uuid.UUID       `json:"org_id"`
	LibraryID   uuid.UUID       `json:"library_id"`
	CreatedBy   uuid.NullUUID   `json:"created_by"`
	Title       string          `json:"title"`
	Slug        string          `json:"slug"`
	Description string          `json:"description"`
	ContentJson json.RawMessage `json:"content_json"`
	Tags        []string        `json:"tags"`
	FolderPath  sql.NullString  `json:"folder_path"`
	StoragePath sql.NullString  `json:"storage_path"`
	Status      string          `json:"status"`
	DeletedAt   sql.NullTime    `json:"deleted_at"`
}

type H5pContentFolder struct {
	ID        uuid.UUID     `json:"id"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	OrgID     uuid.UUID     `json:"org_id"`
	ParentID  uuid.NullUUID `json:"parent_id"`
	Name      string        `json:"name"`
}

type H5pHubCache struct {
	ID        uuid.UUID       `json:"id"`
	CreatedAt time.Time       `json:"created_at"`
	CacheKey  string          `json:"cache_key"`
	Data      json.RawMessage `json:"data"`
	ExpiresAt time.Time       `json:"expires_at"`
}

type H5pHubRegistration struct {
	ID         uuid.UUID `json:"id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	OrgID      uuid.UUID `json:"org_id"`
	SiteKey    string    `json:"site_key"`
	SiteSecret string    `json:"site_secret"`
	HubUrl     string    `json:"hub_url"`
}

type H5pLibrary struct {
	ID            uuid.UUID             `json:"id"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
	MachineName   string                `json:"machine_name"`
	MajorVersion  int32                 `json:"major_version"`
	MinorVersion  int32                 `json:"minor_version"`
	PatchVersion  int32                 `json:"patch_version"`
	Title         string                `json:"title"`
	Origin        string                `json:"origin"`
	MetadataJson  pqtype.NullRawMessage `json:"metadata_json"`
	Categories    []string              `json:"categories"`
	Keywords      []string              `json:"keywords"`
	Screenshots   []string              `json:"screenshots"`
	Description   string                `json:"description"`
	IconPath      sql.NullString        `json:"icon_path"`
	PackagePath   sql.NullString        `json:"package_path"`
	ExtractedPath sql.NullString        `json:"extracted_path"`
	Runnable      bool                  `json:"runnable"`
	Restricted    bool                  `json:"restricted"`
}

type H5pLibraryDependency struct {
	ID             uuid.UUID `json:"id"`
	LibraryID      uuid.UUID `json:"library_id"`
	DependsOnID    uuid.UUID `json:"depends_on_id"`
	DependencyType string    `json:"dependency_type"`
}

type H5pOrgLibrary struct {
	ID         uuid.UUID `json:"id"`
	CreatedAt  time.Time `json:"created_at"`
	OrgID      uuid.UUID `json:"org_id"`
	LibraryID  uuid.UUID `json:"library_id"`
	Enabled    bool      `json:"enabled"`
	Restricted bool      `json:"restricted"`
}

type Organisation struct {
	ID                     uuid.UUID      `json:"id"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
	Name                   string         `json:"name"`
	Slug                   string         `json:"slug"`
	LogoUrl                string         `json:"logo_url"`
	LogoAvatarUrl          string         `json:"logo_avatar_url"`
	PrimaryColor           string         `json:"primary_color"`
	SecondaryColor         string         `json:"secondary_color"`
	AccentColor            string         `json:"accent_color"`
	AccentGradient         string         `json:"accent_gradient"`
	Email                  string         `json:"email"`
	Phone                  string         `json:"phone"`
	Website                string         `json:"website"`
	Status                 string         `json:"status"`
	SubscriptionTier       string         `json:"subscription_tier"`
	SubscriptionID         string         `json:"subscription_id"`
	SubscriptionEnd        sql.NullTime   `json:"subscription_end"`
	StripeCustomerID       string         `json:"stripe_customer_id"`
	AiGenerationsThisMonth int32          `json:"ai_generations_this_month"`
	AiGenerationsResetAt   sql.NullTime   `json:"ai_generations_reset_at"`
	IsFreemium             bool           `json:"is_freemium"`
	FreemiumReason         sql.NullString `json:"freemium_reason"`
	FreemiumExpiresAt      sql.NullTime   `json:"freemium_expires_at"`
	FreemiumGrantedAt      sql.NullTime   `json:"freemium_granted_at"`
	FreemiumGrantedBy      sql.NullString `json:"freemium_granted_by"`
	DeletedAt              sql.NullTime   `json:"deleted_at"`
	DeletionScheduledFor   sql.NullTime   `json:"deletion_scheduled_for"`
}

type OrganisationMembership struct {
	ID             uuid.UUID     `json:"id"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
	UserID         uuid.UUID     `json:"user_id"`
	OrganisationID uuid.UUID     `json:"organisation_id"`
	Role           string        `json:"role"`
	DisplayName    string        `json:"display_name"`
	Status         string        `json:"status"`
	InvitedAt      sql.NullTime  `json:"invited_at"`
	InvitedBy      uuid.NullUUID `json:"invited_by"`
	AcceptedAt     sql.NullTime  `json:"accepted_at"`
}

type ProgressRecord struct {
	ID          uuid.UUID      `json:"id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	OrgID       uuid.UUID      `json:"org_id"`
	EnrolmentID uuid.UUID      `json:"enrolment_id"`
	ContentID   uuid.UUID      `json:"content_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Score       sql.NullString `json:"score"`
	MaxScore    sql.NullString `json:"max_score"`
	Completion  string         `json:"completion"`
	Completed   bool           `json:"completed"`
	Attempts    int32          `json:"attempts"`
	TimeSpent   int32          `json:"time_spent"`
}

type Token struct {
	ID       string    `json:"id"`
	Expires  time.Time `json:"expires"`
	Target   string    `json:"target"`
	Callback string    `json:"callback"`
}

type User struct {
	ID                    uuid.UUID      `json:"id"`
	Created               time.Time      `json:"created"`
	Updated               time.Time      `json:"updated"`
	Email                 string         `json:"email"`
	Phone                 string         `json:"phone"`
	Access                int64          `json:"access"`
	Sub                   string         `json:"sub"`
	Avatar                string         `json:"avatar"`
	CustomerID            string         `json:"customer_id"`
	SubscriptionID        string         `json:"subscription_id"`
	SubscriptionEnd       time.Time      `json:"subscription_end"`
	ApiKey                string         `json:"api_key"`
	DefaultOrganisationID uuid.NullUUID  `json:"default_organisation_id"`
	Suspended             bool           `json:"suspended"`
	SuspendedAt           sql.NullTime   `json:"suspended_at"`
	SuspendedReason       sql.NullString `json:"suspended_reason"`
}

type XapiStatement struct {
	ID        uuid.UUID       `json:"id"`
	CreatedAt time.Time       `json:"created_at"`
	OrgID     uuid.UUID       `json:"org_id"`
	UserID    uuid.UUID       `json:"user_id"`
	ContentID uuid.NullUUID   `json:"content_id"`
	Verb      string          `json:"verb"`
	Statement json.RawMessage `json:"statement"`
}
