// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptPendingMemberships(ctx context.Context, userID uuid.UUID) error
	DeleteTokens(ctx context.Context) error
	DowngradeOrganisationToFree(ctx context.Context, id uuid.UUID) error
	// =============================================================================
	// Organisation Billing Queries (Platform Subscriptions)
	// =============================================================================
	GetOrganisationBillingInfo(ctx context.Context, id uuid.UUID) (GetOrganisationBillingInfoRow, error)
	GetOrganisationByStripeCustomer(ctx context.Context, stripeCustomerID string) (Organisation, error)
	InsertToken(ctx context.Context, arg InsertTokenParams) (Token, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	SelectToken(ctx context.Context, id string) (Token, error)
	SelectUser(ctx context.Context, id uuid.UUID) (User, error)
	SelectUserByCustomerID(ctx context.Context, customerID string) (User, error)
	SelectUserByEmail(ctx context.Context, email string) (User, error)
	SelectUserByEmailAndSub(ctx context.Context, arg SelectUserByEmailAndSubParams) (User, error)
	SelectUsers(ctx context.Context) ([]User, error)
	UpdateOrganisationStripeCustomer(ctx context.Context, arg UpdateOrganisationStripeCustomerParams) error
	UpdateOrganisationSubscription(ctx context.Context, arg UpdateOrganisationSubscriptionParams) error
	UpdateToken(ctx context.Context, arg UpdateTokenParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserAccess(ctx context.Context, arg UpdateUserAccessParams) (User, error)
	UpdateUserActivity(ctx context.Context, id uuid.UUID) error
	UpdateUserCustomerID(ctx context.Context, arg UpdateUserCustomerIDParams) error
	UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error
	UpdateUserSub(ctx context.Context, arg UpdateUserSubParams) error
	UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) error
}

var _ Querier = (*Queries)(nil)
