// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_postgres.sql

package query

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const acceptPendingMemberships = `-- name: AcceptPendingMemberships :exec
update organisation_memberships set accepted_at = current_timestamp, updated_at = current_timestamp where user_id = $1 and accepted_at is null
`

func (q *Queries) AcceptPendingMemberships(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, acceptPendingMemberships, userID)
	return err
}

const deleteTokens = `-- name: DeleteTokens :exec
delete from tokens where expires < current_timestamp
`

func (q *Queries) DeleteTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTokens)
	return err
}

const downgradeOrganisationToFree = `-- name: DowngradeOrganisationToFree :exec
UPDATE organisations
SET
    subscription_tier = 'free',
    subscription_id = '',
    subscription_end = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DowngradeOrganisationToFree(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, downgradeOrganisationToFree, id)
	return err
}

const getOrganisationBillingInfo = `-- name: GetOrganisationBillingInfo :one

SELECT
    id,
    name,
    slug,
    subscription_tier,
    subscription_id,
    subscription_end,
    stripe_customer_id,
    ai_generations_this_month,
    ai_generations_reset_at,
    is_freemium,
    freemium_expires_at
FROM organisations
WHERE id = $1
`

type GetOrganisationBillingInfoRow struct {
	ID                     uuid.UUID    `json:"id"`
	Name                   string       `json:"name"`
	Slug                   string       `json:"slug"`
	SubscriptionTier       string       `json:"subscription_tier"`
	SubscriptionID         string       `json:"subscription_id"`
	SubscriptionEnd        sql.NullTime `json:"subscription_end"`
	StripeCustomerID       string       `json:"stripe_customer_id"`
	AiGenerationsThisMonth int32        `json:"ai_generations_this_month"`
	AiGenerationsResetAt   sql.NullTime `json:"ai_generations_reset_at"`
	IsFreemium             bool         `json:"is_freemium"`
	FreemiumExpiresAt      sql.NullTime `json:"freemium_expires_at"`
}

// =============================================================================
// Organisation Billing Queries (Platform Subscriptions)
// =============================================================================
func (q *Queries) GetOrganisationBillingInfo(ctx context.Context, id uuid.UUID) (GetOrganisationBillingInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getOrganisationBillingInfo, id)
	var i GetOrganisationBillingInfoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SubscriptionTier,
		&i.SubscriptionID,
		&i.SubscriptionEnd,
		&i.StripeCustomerID,
		&i.AiGenerationsThisMonth,
		&i.AiGenerationsResetAt,
		&i.IsFreemium,
		&i.FreemiumExpiresAt,
	)
	return i, err
}

const getOrganisationByStripeCustomer = `-- name: GetOrganisationByStripeCustomer :one
SELECT id, created_at, updated_at, name, slug, logo_url, logo_avatar_url, primary_color, secondary_color, accent_color, accent_gradient, email, phone, website, status, subscription_tier, subscription_id, subscription_end, stripe_customer_id, ai_generations_this_month, ai_generations_reset_at, is_freemium, freemium_reason, freemium_expires_at, freemium_granted_at, freemium_granted_by, deleted_at, deletion_scheduled_for FROM organisations
WHERE stripe_customer_id = $1
`

func (q *Queries) GetOrganisationByStripeCustomer(ctx context.Context, stripeCustomerID string) (Organisation, error) {
	row := q.db.QueryRowContext(ctx, getOrganisationByStripeCustomer, stripeCustomerID)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.LogoAvatarUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.AccentGradient,
		&i.Email,
		&i.Phone,
		&i.Website,
		&i.Status,
		&i.SubscriptionTier,
		&i.SubscriptionID,
		&i.SubscriptionEnd,
		&i.StripeCustomerID,
		&i.AiGenerationsThisMonth,
		&i.AiGenerationsResetAt,
		&i.IsFreemium,
		&i.FreemiumReason,
		&i.FreemiumExpiresAt,
		&i.FreemiumGrantedAt,
		&i.FreemiumGrantedBy,
		&i.DeletedAt,
		&i.DeletionScheduledFor,
	)
	return i, err
}

const insertToken = `-- name: InsertToken :one
insert into tokens (id, expires, target, callback) values ($1, $2, $3, $4) returning id, expires, target, callback
`

type InsertTokenParams struct {
	ID       string    `json:"id"`
	Expires  time.Time `json:"expires"`
	Target   string    `json:"target"`
	Callback string    `json:"callback"`
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, insertToken,
		arg.ID,
		arg.Expires,
		arg.Target,
		arg.Callback,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Expires,
		&i.Target,
		&i.Callback,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
insert into users (id, email, access, sub, avatar, api_key) values ($1, $2, $3, $4, $5, $6) returning id, created, updated, email, phone, access, sub, avatar, customer_id, subscription_id, subscription_end, api_key, default_organisation_id, suspended, suspended_at, suspended_reason
`

type InsertUserParams struct {
	ID     uuid.UUID `json:"id"`
	Email  string    `json:"email"`
	Access int64     `json:"access"`
	Sub    string    `json:"sub"`
	Avatar string    `json:"avatar"`
	ApiKey string    `json:"api_key"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.Access,
		arg.Sub,
		arg.Avatar,
		arg.ApiKey,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionEnd,
		&i.ApiKey,
		&i.DefaultOrganisationID,
		&i.Suspended,
		&i.SuspendedAt,
		&i.SuspendedReason,
	)
	return i, err
}

const selectToken = `-- name: SelectToken :one
select id, expires, target, callback from tokens where id = $1
`

func (q *Queries) SelectToken(ctx context.Context, id string) (Token, error) {
	row := q.db.QueryRowContext(ctx, selectToken, id)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Expires,
		&i.Target,
		&i.Callback,
	)
	return i, err
}

const selectUser = `-- name: SelectUser :one
select id, created, updated, email, phone, access, sub, avatar, customer_id, subscription_id, subscription_end, api_key, default_organisation_id, suspended, suspended_at, suspended_reason from users where id = $1
`

func (q *Queries) SelectUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionEnd,
		&i.ApiKey,
		&i.DefaultOrganisationID,
		&i.Suspended,
		&i.SuspendedAt,
		&i.SuspendedReason,
	)
	return i, err
}

const selectUserByCustomerID = `-- name: SelectUserByCustomerID :one
select id, created, updated, email, phone, access, sub, avatar, customer_id, subscription_id, subscription_end, api_key, default_organisation_id, suspended, suspended_at, suspended_reason from users where customer_id = $1
`

func (q *Queries) SelectUserByCustomerID(ctx context.Context, customerID string) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUserByCustomerID, customerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionEnd,
		&i.ApiKey,
		&i.DefaultOrganisationID,
		&i.Suspended,
		&i.SuspendedAt,
		&i.SuspendedReason,
	)
	return i, err
}

const selectUserByEmail = `-- name: SelectUserByEmail :one
select id, created, updated, email, phone, access, sub, avatar, customer_id, subscription_id, subscription_end, api_key, default_organisation_id, suspended, suspended_at, suspended_reason from users where email = $1
`

func (q *Queries) SelectUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionEnd,
		&i.ApiKey,
		&i.DefaultOrganisationID,
		&i.Suspended,
		&i.SuspendedAt,
		&i.SuspendedReason,
	)
	return i, err
}

const selectUserByEmailAndSub = `-- name: SelectUserByEmailAndSub :one
select id, created, updated, email, phone, access, sub, avatar, customer_id, subscription_id, subscription_end, api_key, default_organisation_id, suspended, suspended_at, suspended_reason from users where email = $1 and sub = $2
`

type SelectUserByEmailAndSubParams struct {
	Email string `json:"email"`
	Sub   string `json:"sub"`
}

func (q *Queries) SelectUserByEmailAndSub(ctx context.Context, arg SelectUserByEmailAndSubParams) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUserByEmailAndSub, arg.Email, arg.Sub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionEnd,
		&i.ApiKey,
		&i.DefaultOrganisationID,
		&i.Suspended,
		&i.SuspendedAt,
		&i.SuspendedReason,
	)
	return i, err
}

const selectUsers = `-- name: SelectUsers :many
select id, created, updated, email, phone, access, sub, avatar, customer_id, subscription_id, subscription_end, api_key, default_organisation_id, suspended, suspended_at, suspended_reason from users
`

func (q *Queries) SelectUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, selectUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Updated,
			&i.Email,
			&i.Phone,
			&i.Access,
			&i.Sub,
			&i.Avatar,
			&i.CustomerID,
			&i.SubscriptionID,
			&i.SubscriptionEnd,
			&i.ApiKey,
			&i.DefaultOrganisationID,
			&i.Suspended,
			&i.SuspendedAt,
			&i.SuspendedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganisationStripeCustomer = `-- name: UpdateOrganisationStripeCustomer :exec
UPDATE organisations
SET stripe_customer_id = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateOrganisationStripeCustomerParams struct {
	ID               uuid.UUID `json:"id"`
	StripeCustomerID string    `json:"stripe_customer_id"`
}

func (q *Queries) UpdateOrganisationStripeCustomer(ctx context.Context, arg UpdateOrganisationStripeCustomerParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganisationStripeCustomer, arg.ID, arg.StripeCustomerID)
	return err
}

const updateOrganisationSubscription = `-- name: UpdateOrganisationSubscription :exec
UPDATE organisations
SET
    subscription_tier = $2,
    subscription_id = $3,
    subscription_end = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateOrganisationSubscriptionParams struct {
	ID               uuid.UUID    `json:"id"`
	SubscriptionTier string       `json:"subscription_tier"`
	SubscriptionID   string       `json:"subscription_id"`
	SubscriptionEnd  sql.NullTime `json:"subscription_end"`
}

func (q *Queries) UpdateOrganisationSubscription(ctx context.Context, arg UpdateOrganisationSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganisationSubscription,
		arg.ID,
		arg.SubscriptionTier,
		arg.SubscriptionID,
		arg.SubscriptionEnd,
	)
	return err
}

const updateToken = `-- name: UpdateToken :exec
update tokens set expires = $1 where id = $2 returning id, expires, target, callback
`

type UpdateTokenParams struct {
	Expires time.Time `json:"expires"`
	ID      string    `json:"id"`
}

func (q *Queries) UpdateToken(ctx context.Context, arg UpdateTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateToken, arg.Expires, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
update users set
    email = $1,
    phone = $2,
    access = $3,
    avatar = $4,
    subscription_id = $5,
    subscription_end = $6,
    api_key = $7,
    updated = current_timestamp
where id = $8 returning id, created, updated, email, phone, access, sub, avatar, customer_id, subscription_id, subscription_end, api_key, default_organisation_id, suspended, suspended_at, suspended_reason
`

type UpdateUserParams struct {
	Email           string    `json:"email"`
	Phone           string    `json:"phone"`
	Access          int64     `json:"access"`
	Avatar          string    `json:"avatar"`
	SubscriptionID  string    `json:"subscription_id"`
	SubscriptionEnd time.Time `json:"subscription_end"`
	ApiKey          string    `json:"api_key"`
	ID              uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Email,
		arg.Phone,
		arg.Access,
		arg.Avatar,
		arg.SubscriptionID,
		arg.SubscriptionEnd,
		arg.ApiKey,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionEnd,
		&i.ApiKey,
		&i.DefaultOrganisationID,
		&i.Suspended,
		&i.SuspendedAt,
		&i.SuspendedReason,
	)
	return i, err
}

const updateUserAccess = `-- name: UpdateUserAccess :one
update users set access = $1 where id = $2 returning id, created, updated, email, phone, access, sub, avatar, customer_id, subscription_id, subscription_end, api_key, default_organisation_id, suspended, suspended_at, suspended_reason
`

type UpdateUserAccessParams struct {
	Access int64     `json:"access"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserAccess(ctx context.Context, arg UpdateUserAccessParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserAccess, arg.Access, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionEnd,
		&i.ApiKey,
		&i.DefaultOrganisationID,
		&i.Suspended,
		&i.SuspendedAt,
		&i.SuspendedReason,
	)
	return i, err
}

const updateUserActivity = `-- name: UpdateUserActivity :exec
update users set updated = current_timestamp where id = $1
`

func (q *Queries) UpdateUserActivity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateUserActivity, id)
	return err
}

const updateUserCustomerID = `-- name: UpdateUserCustomerID :exec
update users set customer_id = $1 where id = $2
`

type UpdateUserCustomerIDParams struct {
	CustomerID string    `json:"customer_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserCustomerID(ctx context.Context, arg UpdateUserCustomerIDParams) error {
	_, err := q.db.ExecContext(ctx, updateUserCustomerID, arg.CustomerID, arg.ID)
	return err
}

const updateUserPhone = `-- name: UpdateUserPhone :exec
update users set phone = $2 where id = $1
`

type UpdateUserPhoneParams struct {
	ID    uuid.UUID `json:"id"`
	Phone string    `json:"phone"`
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPhone, arg.ID, arg.Phone)
	return err
}

const updateUserSub = `-- name: UpdateUserSub :exec
update users set sub = $2 where id = $1
`

type UpdateUserSubParams struct {
	ID  uuid.UUID `json:"id"`
	Sub string    `json:"sub"`
}

func (q *Queries) UpdateUserSub(ctx context.Context, arg UpdateUserSubParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSub, arg.ID, arg.Sub)
	return err
}

const updateUserSubscription = `-- name: UpdateUserSubscription :exec
update users set access = $1, subscription_id = $2, subscription_end = $3 where customer_id = $4
`

type UpdateUserSubscriptionParams struct {
	Access          int64     `json:"access"`
	SubscriptionID  string    `json:"subscription_id"`
	SubscriptionEnd time.Time `json:"subscription_end"`
	CustomerID      string    `json:"customer_id"`
}

func (q *Queries) UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSubscription,
		arg.Access,
		arg.SubscriptionID,
		arg.SubscriptionEnd,
		arg.CustomerID,
	)
	return err
}
